### ISSUE TITLE
STATUS_INTERNAL_ERROR: Unknown error in injected assembler code. (Code: 5)

### ISSUE THREAD

**Issue by wpfpro** [EasyHook/EasyHook#31] opened 2015-08-20 05:08 UTC
I've just made a simple test with EasyHook 2.7 binaries but it did not work and threw the exception as in the question title. I tried the same with EasyHook 2.6 (of course the code is a little different because it requires registering dlls to GAC) and it worked OK.

Here is the test project I made https://drive.google.com/file/d/0B9pRIB5Qqb08STZpdXNBUkU5LWc/view?usp=sharing

I've tried both 3.5 and 4.0 binaries files and also changed the .NET Framework Target of all projects in my test variously but still not working (with the same exception).

In my test project, I try using RemoteHooking.CreateAndInject. 
However when using RemoteHooking.Inject, there is not any exception but it does not seem to hook successfully. As in my test, when closing the target process, a message box should appear but it does not.

 Other info: I'm using VS2012, Windows 7 Ultimate 64 bit and again the important thing is EasyHook2.6 works with almost the same code.

Could you see and let me know what's actually wrong here?

**Comment by spazzarama** [comment] 2015-08-20 10:52
There is a bug in CreateAndInject for the current binaries that has been fixed last week, I'll be preparing a new binary build this weekend.

Note: you can change the tools version in the projects to compile with VS2012.

**Comment by spazzarama** [comment] 2015-08-20 10:54
Duplicate of #9

**Closed by spazzarama** 2015-08-20 10:54 UTC

**Comment by wpfpro** [comment] 2015-08-20 22:15
I'm not sure if that's the same problem because as I said RemoteHooking.Inject aso does not work (although there is not any exception).

**Comment by spazzarama** [comment] 2015-08-20 22:29
I'll check it over the weekend

**Comment by spazzarama** [comment] 2015-08-23 02:01
@wpfpro the problem (aside from the original CreateAndInject bug) is the way you have created your delegate:

Instead of using `new Action<int>(..)` to pass in your hook handler reference `localHook = LocalHook.Create(LocalHook.GetProcAddress("kernel32.dll", "ExitProcess"), new Action<int>(ExitProcessHook), this);`

You need to use a real delegate and specify the UnmanagedFunctionPoint attribute, as in the following:
```c#
[UnmanagedFunctionPointer(CallingConvention.StdCall,
            CharSet = CharSet.Unicode,
            SetLastError = true)]
        delegate void ExitProcessDelegate(int exitCode);
...
localHook = LocalHook.Create(LocalHook.GetProcAddress("kernel32.dll", "ExitProcess"), 
    new ExitProcessDelegate(ExitProcessHook), this);
```

After making this change, your example worked correctly.

**Comment by spazzarama** [comment] 2015-08-23 02:05
Just for completeness, the above sample works with or without the `UnmanagedFunctionPointer` attribute.

**Comment by wpfpro** [comment] 2015-08-26 03:51
I've tried changing it to use a declared delegate instead as you said but it's still not working on my side. I doubt there should be something different on your machine making it working such as your GAC_MSIL folder might already contain some cached version of your EasyHook binaries. At least I've encountered the same situation when the test seemed to be OK but then I found out that it failed to work when there are no EasyHook binaries cached in GAC_MSIL. From that experience, I always clear the gac before running the test. I hope the final (stable) version of Easyhook2.7 will be released soon.

**Comment by spazzarama** [comment] 2015-08-26 11:56
I have no EasyHook binaries within GAC_MSIL, and everything is working fine, there should be no reason for you to need the GAC if using the "no GAC" approach - i.e. make sure you provide the full path to the assemblies you are injecting.

Btw - are you still getting an error or just the target app doesn't "appear", i.e. stays suspended?

**Comment by wpfpro** [comment] 2015-08-26 14:13
It's the same as before modifying the code (throws the same exception when using CreateAndInject and silently run but the target is not hooked when using Inject).

**Comment by spazzarama** [comment] 2015-08-29 11:52
Please try with the new release: https://github.com/EasyHook/EasyHook/releases/tag/v2.7.5719.0

Example:
Run `FileMon.exe`
enter `"C:\Windows\notepad.exe"`

When notepad.exe launches, select File - Open, you should see the hooked messages.

**Comment by wpfpro** [comment] 2015-08-30 09:23
Thank you. It worked perfectly now (both Inject and CreateAndInject)!
